#!/bin/bash
readthisone() {
	echo ""
	echo "######################################################"
	echo "######################################################"
	echo "##################### READ THIS ######################"
	echo "######################################################"
	echo "######################################################"
	echo "## Dear GitHub user, please do not copy this script ##"
	echo "######################################################"
	echo "##  All copyright under the laws of all countries   ##"
	echo "######################################################"
	echo "##        Copyright of  GH05T HUNTER5, 2023         ##"
	echo "######################################################"
	echo "######################################################"
}

if [ -z $1 ]; then
	echo "Retry invalid option"
	exit
elif [[ $1 = "--brute" && $2 = "--install" && $3 = "json" ]]; then
		wget -O ~/instapy-config.json "https://git.io/v5DGy" >/dev/null 2>&1
		if [ -f ~/instapy-config.json ]; then
			echo ''
		else
			cd ~
			wget -O ~/instapy-config.json "https://git.io/v5DGy" >/dev/null 2>&1
		fi
elif [[ $1 = "--brute" && $2 = "--uninstall" && $3 = "json" ]]; then
	rm ~/instapy-config.json >/dev/null 2>&1
	if [ -f ~/instapy-config.json ]; then
		rm -r ~/instapy-config.json >/dev/null 2>&1
	else
		echo ''
	fi
	if [ -f instapy-config.json ]; then
		rm instapy-config.json
	else
		echo ''
	fi	
else
	echo "Retry invalid option"
	exit
fi
